In [19]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns',9999)
pd.set_option('display.max_rows',9999)

In [71]:
df_raw = pd.read_csv('../datasets/credit_score_classification/train.csv')

C:\Users\Iverson\AppData\Local\Temp\ipykernel_9004\2240171195.py:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw = pd.read_csv('../datasets/credit_score_classification/train.csv')

# Preprocessing

In [75]:
df = df_raw.copy()

# Force To Int
force_int_col = ['Age','Annual_Income','Monthly_Inhand_Salary','Num_of_Loan','Delay_from_due_date',
                 'Changed_Credit_Limit','Outstanding_Debt','Amount_invested_monthly','Monthly_Balance']

pattern = r'[\D]*'

for col in force_int_col:
    if df[col].dtypes not in ['O']: 
        continue

    try:
        df[col] = df[col].str.replace(pattern,'',regex=True).fillna(0).astype(int)
    except OverflowError:
        print(col,' too big, convert to float instead')
        df[col] = df[col].str.replace(pattern,'',regex=True).fillna(0).astype(float)

Annual_Income  too big, convert to float instead

ValueError: invalid literal for int() with base 10: ''

In [61]:
dropped_col = []

for col in df.columns:
    print(col)
    dtypes = df[col].dtypes
    print(f'Dtypes',{dtypes})

    if dtypes == 'O':
        continue

    num_instances = df[col].nunique()
    print(f'Num Instance', num_instances)
    if num_instances <=10:
        print(f'Unique Instance',df[col].unique())

    print('Num Nulls',df[col].isnull().sum())
    print('-------')

    if dtypes == 'O' and num_instances >= 1000:
        dropped_col.append(col)

ID
Dtypes {dtype('O')}
Num Instance 100000
Num Nulls 0
-------
Customer_ID
Dtypes {dtype('O')}
Num Instance 12500
Num Nulls 0
-------
Month
Dtypes {dtype('O')}
Num Instance 8
Unique Instance ['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August']
Num Nulls 0
-------
Name
Dtypes {dtype('O')}
Num Instance 10139
Num Nulls 9985
-------
Age
Dtypes {dtype('float64')}
Num Instance 1728
Num Nulls 0
-------
SSN
Dtypes {dtype('O')}
Num Instance 12501
Num Nulls 0
-------
Occupation
Dtypes {dtype('O')}
Num Instance 16
Num Nulls 0
-------
Annual_Income
Dtypes {dtype('float64')}
Num Instance 13487
Num Nulls 0
-------
Monthly_Inhand_Salary
Dtypes {dtype('float64')}
Num Instance 13235
Num Nulls 15002
-------
Num_Bank_Accounts
Dtypes {dtype('int64')}
Num Instance 943
Num Nulls 0
-------
Num_Credit_Card
Dtypes {dtype('int64')}
Num Instance 1179
Num Nulls 0
-------
Interest_Rate
Dtypes {dtype('int64')}
Num Instance 1750
Num Nulls 0
-------
Num_of_Loan
Dtypes {dtype('float64')}
Num Instance 413
Num Nulls 0
-------
Type_of_Loan
Dtypes {dtype('O')}
Num Instance 6260
Num Nulls 11408
-------
Delay_from_due_date
Dtypes {dtype('float64')}
Num Instance 73
Num Nulls 0
-------
Num_of_Delayed_Payment
Dtypes {dtype('O')}
Num Instance 749
Num Nulls 7002
-------
Changed_Credit_Limit
Dtypes {dtype('O')}
Num Instance 4384
Num Nulls 0
-------
Num_Credit_Inquiries
Dtypes {dtype('float64')}
Num Instance 1223
Num Nulls 1965
-------
Credit_Mix
Dtypes {dtype('O')}
Num Instance 4
Unique Instance ['_' 'Good' 'Standard' 'Bad']
Num Nulls 0
-------
Outstanding_Debt
Dtypes {dtype('O')}
Num Instance 13178
Num Nulls 0
-------
Credit_Utilization_Ratio
Dtypes {dtype('float64')}
Num Instance 100000
Num Nulls 0
-------
Credit_History_Age
Dtypes {dtype('O')}
Num Instance 404
Num Nulls 9030
-------
Payment_of_Min_Amount
Dtypes {dtype('O')}
Num Instance 3
Unique Instance ['No' 'NM' 'Yes']
Num Nulls 0
-------
Total_EMI_per_month
Dtypes {dtype('float64')}
Num Instance 14950
Num Nulls 0
-------
Amount_invested_monthly
Dtypes {dtype('O')}
Num Instance 91049
Num Nulls 4479
-------
Payment_Behaviour
Dtypes {dtype('O')}
Num Instance 7
Unique Instance ['High_spent_Small_value_payments' 'Low_spent_Large_value_payments'
 'Low_spent_Medium_value_payments' 'Low_spent_Small_value_payments'
 'High_spent_Medium_value_payments' '!@9#%8'
 'High_spent_Large_value_payments']
Num Nulls 0
-------
Monthly_Balance
Dtypes {dtype('O')}
Num Instance 98792
Num Nulls 1200
-------
Credit_Score
Dtypes {dtype('O')}
Num Instance 3
Unique Instance ['Good' 'Standard' 'Poor']
Num Nulls 0
-------